# Docs for the Azure Web Apps Deploy action: https://go.microsoft.com/fwlink/?linkid=2134798
# More GitHub Actions for Azure: https://go.microsoft.com/fwlink/?linkid=2135048

name: Azure App Service - Datapal(Production), Build and deploy Spring app

on:
  push:
    branches:
      - release

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@master


    - name: Set up Java version
      uses: actions/setup-java@v1
      with:
        java-version: '11'
    - name: Blah
      run: cd vaadin-crm
    - name: sd
      run: dir
    - name: Build with Maven
      run: mvn clean install

    - name: Run Azure webapp deploy action using publish profile credentials
      uses: azure/webapps-deploy@v2
      with:
        app-name: Datapal
        slot-name: Production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_B6931C5635C14F7EB57A06FDFB67C3CC }}
        package: ${{ github.workspace }}/vaadin-crm/target/*.jar

